language: python

sudo: false

notifications:
  email: false

# For Pypandoc to work, it needs pandoc to be installed
addons:
  apt_packages:
    - pandoc

python:
  - 3.5

env:
  global:
    - secure: UkXMWiCMn2B4deXOVISAEAKjMm+KgPN+HGicPHNoMqo+h09WBUX081F+AW1eab06NWgDiGB6h+2lAsPbcmVtQ7Xu1mHGrIT6EU7iFMAvG7qwAdTD8npJNoGKlCxzy1R2iN74MBVMp+QpBAdgz9Xu147WQfinfy38RJW5Nspz/Kpte3QII0VITlCp2il9wRxKe4/tWVg8sUEHfzbJdJNvuAwjOPV6o5dHA6uKfbPFQ02qHMJKb1pimwrj4bRi35Ssk6ysYqdfDqveqtqBwlfZZhnfxrqz0uCkl9/9KRi2VupGnsbT7gzehsVLs99wrWGVL5rztmLEJ4D29nEkXSCLj6OVC8eXrTw29HuDS28IWSZerrVTAlPlyWQ+vuWk1K9WX3x+Li7tiKjallUMDP4B6VBFJxEtxqBO5pDBtAKRe8M8UC26ZkLSz6wA1bS1D1sLycvyL7iVh1bbu/ExF+FhUKm0RcJJ+gQxIgK0V/xMkduyv9JB9jebarh4LDSCriykTAg+nw06iLZuaOsU6XVr5zMC449kphxe0Fh67AnMS46qm1wf75X7LwmqPyQBUa+3Y9a/3BScWITXqw5bqY9IyOrQ6s3pG8r9WwaIle46PAqOzfYEZdL1xI9N6NWnvbDET33G5/IE0eJiIKnOsQHQDBuWwOzAnQDcNYUL0x/WQaE=
    - secure: eXuhZkWx7l+5goO5gN6pF0lwTgbSKB5Qt4uW5Bpu77oaAoU39kLQ+UNF9SkdjwQg2/3Y/4JwjLIi9uEXAHXA6F2NLAJbgAgDjmrTw8WbVpticK+sGYgbTJZFGFo9DaPq6jygmv5y3k+S2GTxUB55lzcmbwndeoa2y+JGFJIiGEkPb2tBGk7ywHUoVz35+/VmVc17+2DRxrpJ62nmIVIpP9tnTUP76pWt9F2YgykOYSGQEIYT0Q7j2lr5A5l/dPtZIkPzTcNkUqamQK03F+dDabAPhuWxsPW1IR8P9j4JS8Jzi1x3QfMhQySMwxkKT1PvDH7NjlRvuF+Afgsc7QY8+qTgfjbCS8KBpFDN0ObpVVMPr11psmhOB9zd0ebe/XzErSu2qq1of0HaXm8vjU/i03f3SQWzOgz22HmEFDMyPdq3sOb2UhL5xey2anfclt/HbhGaDeTS5yhpqJR1C0Ivx7/s15HkmkKfmyVTyP/vOG5F9TpsIPDGRQbuET/wL6sbM8+lmziFSwOvhU3kVQRXdoGvx5MZZr98cceYJW40GHXaflmQzy8n4HKjP1igpfnlbEg6aXOaVoj7TUjAwd6PwK2Bg4V/A4RTQ+WsRqL/ybLHNADMTWhqcqlp/mD9uxs8CRi/12VCVaDVfL8R/dfBYSs+72vhrk9oadRhYb5unS0=

before_install:
  - pip install -U pip
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# commands to run tests
script:
  - coverage run --source=nprime.pyprime -m xdoctest nprime
  - pytest --xdoctest --cov=nprime --cov-report xml nprime tests # xml for Codacy

deploy:
  provider: pypi
  user: sylhare
  password:
    secure: h60Fn0vqYbAQP24h/AdTKoqxxgtSrHPtZaRo5r7g87HQbPie741ZvB2olNYm4RjRKLaFgA0gZdCsPmN1LhXEIfVtKZGql7E1Rb1feKCMu+uXnQ0yC5kd+JGuhiceZCR6k8sBsZplDmHXeHDG1ZQT0FsorHniM1uxxIGhfZuB62F23dGR7Go+j62tnLD779UzegaNn6vcWFfPoWwQRVhSONHaGzP+2QNxzRhDSQ8Vo2ABYPIQCueTHsdhkaDS38hzMY7dSBRRkxRLMDXzVs4ZxU4pb0hkvoHbGzpkdiCq5QR94HxuWqwxIWD4z0PkFL/bGG9AEb3QLbvgJgvCt+6Y/ZaPG1IP/4gqDr8GaZ1YbjoSpa6AZd4U2usm2gNFwyQnINkk2kXgj++3pcLB4K6VnGf8jdM3JNGVsneGanSkcXtfJtOFlyfKVcvEbJ9/AlsLr/3ZmfSaGTa4/dfBEnOEAN7MkQCGVuPLmc9E8mzW4evTmICe8nr2so9HcQnFhXnvlWTc5mc/j3xnvp6PKmewQQCO98LAebLvbugM9qFUokIk1bmsyexZC66kJV1ksDQlPRXrVSsLNf/9mYl1MNtOykDr5gr3arTYD3iPui798ZUzNL2i3tiAakMP0WAlsgPHKpvCnCeaPu1oWlEp6i2VA5AXQ1c3LQ/5MWWcIXQ1QcA=
  on:
    tags: true

after_success:
  - pip install nprime
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT    # Code Climate code coverage
  - codecov                                                           # Codecov code coverage
  - python-codacy-coverage -r coverage.xml                            # Codacy code coverage
